{

//conjunto1
CONJ: letra -> a~z;

//conjunto2
CONJ: digito -> 0~9;
CONJ: digito -> 0,1,2,3,4;



//ER1
//ExpReg1 ->.{L} ? |{Q} | {L} {D};
//ExpReg1 ->.{L} + |{Q} | {L} {D};
ExpReg1 ->.{L} ? |{Q} | {L} {D};
//ExpReg1 ->.{L} * |{Q} | {L} {D};

//ExpReg1 ->.|{x}{y}{a};
//ExpReg1 ->.{letra} + |"_" | {letra} {digito};
//ER2
//ExpresionReg2 ->. {digito} ."."+{digito};
//ER3
//RegEx3 ->. {digito} *|"_"| {letra} {digito};

//SEPARACION
%%

//CADENA1
ExpReg1: "primerLexemaCokoa";
//CADENA2
ExpresionReg2 : "34.44";
//FIN
}
