
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int PHRASE = 23;
  public static final int S_DOT = 11;
  public static final int S_PCENTS = 8;
  public static final int RANGE = 19;
  public static final int S_ASTERISK = 13;
  public static final int S_DOTS = 5;
  public static final int S_LA = 3;
  public static final int SPACE = 20;
  public static final int LETTER = 24;
  public static final int S_LINE = 12;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int S_COLON = 10;
  public static final int S_LBREAK = 16;
  public static final int S_SEMICOLON = 6;
  public static final int CONJ = 21;
  public static final int S_DQUOTES = 18;
  public static final int S_QUOTE = 17;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 22;
  public static final int S_PLUS = 14;
  public static final int S_RANK = 9;
  public static final int S_LLC = 4;
  public static final int S_ARROW = 7;
  public static final int S_QMARK = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "S_LA",
  "S_LLC",
  "S_DOTS",
  "S_SEMICOLON",
  "S_ARROW",
  "S_PCENTS",
  "S_RANK",
  "S_COLON",
  "S_DOT",
  "S_LINE",
  "S_ASTERISK",
  "S_PLUS",
  "S_QMARK",
  "S_LBREAK",
  "S_QUOTE",
  "S_DQUOTES",
  "RANGE",
  "SPACE",
  "CONJ",
  "IDENTIFICADOR",
  "PHRASE",
  "LETTER"
  };
}

